on:
  push:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  lookup-user-email:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.actor }}
    - run: npm install @octokit/action
    - uses: actions/github-script@v6
      id: actor-email
      with:
        result-encoding: string
        script: |
          const { Octokit } = require("@octokit/action");
          const octokit = new Octokit()
          await octokit.request('GET /user/emails{?per_page,page}', {})
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Display actor email 
      run: echo "${{steps.actor-email.outputs.result}}"
