on:
  push:

jobs:
  lookup-user-email:
    runs-on: ubuntu-latest
    steps:
    - run: npm install @octokit/action
    - uses: actions/github-script@v6
      id: actor-email
      with:
        result-encoding: string
        script: |
          const { Octokit } = require("@octokit/action");
          const octokit = new Octokit()
          await octokit.request('GET /user/emails{?per_page,page}', {})
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Display actor email 
      run: echo "${{steps.actor-email.outputs.result}}"
